src/Entity/Relation.php
<?php 
namespace App\Entity;

use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

use App\Entity\User;
use App\Entity\Page;

/** @MongoDB\EmbeddedDocument */
class Relation
{

    /** 
     * Reference the Page wich own (publicate) the News
     * @MongoDB\ReferenceOne(targetDocument="Page") 
     */
    private $parent;


    /** 
     * Reference the admins of the Page
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $admins;
    /**
     * @MongoDB\ReferenceMany(targetDocument="Page")
     */
    private $isAdminOf;
    /** 
     * Reference the admins of the Page
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $adminsRequests;


    /** 
     * Reference the friends of the Page
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $friends;
    /** 
     * Reference the friendsRequests of the Page
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $friendsRequests;


    /** 
     * Reference the followers of the Page
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $followers;
    /** 
     * Reference the follows of the Page
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $follows;


    /** 
     * Reference the participants of the Page (event)
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $participants;
    /** 
     * Reference the event Page where this Page participage
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $participateTo;


    
    /** 
     * Reference the likers of the Page
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $likers;
    /** 
     * Reference the page liked by the Page
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $likes;

    /** 
     * Reference the Pages i am able to chat with
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $chatContacts;

    /** 
     * Reference pages white-listed by the Page (favorites)
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $whiteList;
    
    /** 
     * Reference pages black-listed by the Page
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $blackList;

    public function __construct($parent)
    {
        //save the parent Page to enable access to all attributes
        //exemple : $this->parent->getOwner();
        $this->parent = $parent;

        $this->friends = array();
        $this->friendsRequests = array();
        $this->admins = array();
        $this->adminsRequests = array();
        $this->isAdminOf = array();
        $this->followers = array();
        $this->follows = array();
        $this->participants = array();
        $this->participateTo = array();
        $this->likers = array();
        $this->likes = array();
        $this->chatContacts = array();
    }

    /****************************** ADMINS ******************************************/

    /**
     * get admin
     */
    public function getAdmins()
    {   
        return $this->admins;
    }

    /**
     * add admin
     */
    public function addAdmin(Page $page)
    {
        
        if(!$this->getIsAdmin($page->getSlug())){
            $this->admins[] = $page;
            //all admins are friends
            $this->addFriend($page);
            $page->getRelations()->addFriend($this->parent);
            return true;
        }
        else{
            return false;
        }
    }

    /**
     * add admin
     */
    public function addIsAdminOf(Page $page)
    {
        if(!$this->getImAdminOf($page->getSlug())){
            $this->isAdminOf[] = $page;
            //dd("true addIsAdminOf");
            return true;
        }
        else{
            //dd("false addIsAdminOf");
            return false;
        }
    }

    public function getIsAdminOf()
    {
        return $this->isAdminOf;
    }

    public function getImAdminOf($slug)
    {
        foreach ($this->isAdminOf as $key => $page) {
            if($page->getSlug() == $slug) return true;
        }
        return false;
    }
    public function getImAdminOfId($id)
    {
        foreach ($this->isAdminOf as $key => $page) {
            if($page->getId() == $id) return true;
        }
        return false;
    }
    public function getIsAdmin($slug)
    {
        foreach ($this->admins as $key => $page) {
            if($page->getSlug() == $slug) return true;
        }
        return false;
    }
    /* ############# REQUESTS ############# */

        /**
         * get adminsRequests
         */
        public function getAdminsRequests()
        {   
            return $this->adminsRequests;
        }

        /**
         * add AdminsRequests
         */
        public function addAdminRequest(Page $page)
        {
            //add admin if the Page is not already a admin
            //and if it is not the parent (you cant be admin with yourself)
            if(empty($this->adminsRequests) || !$this->adminsRequests->contains($page) && $page != $this->parent){
                $this->adminsRequests[] = $page;
                return true;
            }
            else{
                return false;
            }
        }

        /**
         * remove adminsRequests
         */
        public function removeAdminRequest(Page $page)
        {   
            $this->adminsRequests->removeElement($page);
        }


    /**
     * remove admins
     */
    public function removeAdmin(Page $page)
    {   
        $this->admins->removeElement($page);
    }

    /**
     * remove admins
     */
    public function removeIsAdminOf(Page $page)
    {   
        $this->isAdminOf->removeElement($page);
    }


    /****************************** FRIENDS ******************************************/


    /**
     * get friends : return all pages, no matter of his type
     */
    public function getFriends()
    {   
        return $this->friends;
    }


    /**
     * get friends : return only page with type Page::TYPE_USER
     */
    public function getRealFriends()
    {
        $friends = array();
        foreach ($this->friends as $key => $page) {
            if($page->getType() == Page::TYPE_USER) $friends[] = $page;
        }
        return $friends;
    }

    /**
     * add friends
     */
    public function addFriend(Page $page)
    {
        //add friend if the Page is not already a friend
        //and if it is not the parent (you cant be friend with yourself)
        //dump($page->getId()); dump($this->parent->getId());
        if(!$this->getImFriend($page->getSlug()) && $page != $this->parent){
            $this->friends[] = $page;
            $this->addChatContacts($page);
            return true;
        }
        else{
            return false;
        }
    }

    /**
     * remove friends
     */
    public function removeFriend(Page $page)
    {   
        $this->friends->removeElement($page);
    }

    public function getIsMemberOf()
    {
        $members = array();
        foreach ($this->friends as $key => $page) {
            if($page->getType() != Page::TYPE_USER) $members[] = $page;
        }
        return $members;
        //return $this->isMemberOf;
    }

    public function getImFriend($slug)
    {
        foreach ($this->friends as $key => $page) {
            if($page->getSlug() == $slug) return true;
        }
        return false;
    }

    public function getImMember($slug)
    {
        foreach ($this->friends as $key => $page) {
            if($page->getSlug() == $slug && $page->getType() != Page::TYPE_USER) 
                return true;
        }
        return false;
    }
    
    public function getImFriendId($id)
    {
        foreach ($this->friends as $key => $page) {
            if($page->getId() == $id) return true;
        }
        return false;
    }

    /* ############# REQUESTS ############# */

        /**
         * get friendsRequests
         */
        public function getFriendsRequests()
        {   
            return $this->friendsRequests;
        }

        /**
         * add friendsRequest
         */
        public function addFriendRequest(Page $page)
        {
            //add friend if the Page is not already a friend
            //and if it is not the parent (you cant be friend with yourself)
            if(empty($this->friendsRequests) || !$this->friendsRequests->contains($page) && $page != $this->parent){
                $this->friendsRequests[] = $page;
                return true;
            }
            else{
                return false;
            }
        }

        /**
         * remove friendsRequests
         */
        public function removeFriendRequest(Page $page)
        {   
            $this->friendsRequests->removeElement($page);
        }


    /****************************** FOLLOWERS ****************************************/


    /**
     * get followers
     */
    public function getFollowers()
    {   
        return $this->followers;
    }

    /**
     * add followers
     */
    public function addFollower(Page $page)
    {
        //add follower if the Page is not already a follower
        //and if it is not the parent (you cant be follower of yourself)
        //dd($this->inFollowers($page->getSlug()));
        if(!$this->inFollowers($page->getSlug())){
            $this->followers[] = $page;
            return true;
        }
        else{
            return false;
        }
    }

    /**
     * remove followers
     */
    public function removeFollower(Page $page)
    {   
        $this->followers->removeElement($page);
    }

    /**
     * remove followers
     */
    public function removeFollow(Page $page)
    {   
        $this->follows->removeElement($page);
        return true;
    }

    /**
     * add follows
     */

src/Entity/User.php
<?php
// src/Entity/User.php
namespace App\Entity;

use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

//use Captcha\Bundle\CaptchaBundle\Validator\Constraints as CaptchaAssert;

/**
 * User class contain only minimal informations, needed for login.<br>
 * All other informations about Users are stocked in Page class 
 *
 * @MongoDB\Document(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, \Serializable
{

	const ROLE_DEFAULT = 'ROLE_USER';
    const ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN';

	/**
	 * Auto generated mongoID
     * @MongoDB\Id(strategy="auto")
     */
	private $id;

	/**
     * @MongoDB\Field(type="string")
     */
	private $username;

	/**
     * @MongoDB\Field(type="string")
     */
	private $password;

	/**
     * @MongoDB\Field(type="string")
     */
	private $email;

	/**
	 * By default : false<br>
	 * isActive = true after email validation
     * @MongoDB\Field(type="boolean")
     */
	private $isActive;

	
	/**
     * @MongoDB\Field(type="collection")
     */
	private $roles;

    
	/** @MongoDB\NotSaved */
    private $plainPassword;

	/**
     * @MongoDB\Field(type="date")
     */
    private $passwordRequestedAt;

    /**
     * @MongoDB\Field(type="string")
     */
    private $token;


	/**
	 * Date initialized when user register
	 * Set one time, never modified after initialization
     * @MongoDB\Field(type="date")
     */
    private $created;

    /**
     * @MongoDB\ReferenceMany(targetDocument="Page", mappedBy="owner")
     */
    private $pages;

    /**
	 * ImageProfil are not register in User data.<br>
	 * This attribute allow us to retrieve ImageProfil from the Page linked to the user<br>
	 * Only to display ImageProfil in TopMenu from app.user
    */
    private $imageProfil;

	/**
	 * By default : false<br>
	 * isActive = true after email validation
     * @MongoDB\Field(type="boolean")
     */
	private $isSuperAdmin;



	public function __construct()
	{
		$this->isActive = true;
		$this->roles = ['ROLE_USER'];
		$this->token = bin2hex(random_bytes(20)); // 20 chars //$this->chatToken;
		$this->created = new \Datetime();
	}
    
	/*
	 * Get id
	 */
	public function getId()
	{
		return $this->id;
	}

	public function getRealUsername()
	{
		return $this->username;
	}
	public function getUsername()
	{
		return $this->email;
	}

	public function setUsername($username)
	{
		$this->username = $username;
		return $this;
	}


	public function getPassword()
	{
		return $this->password;
	}

	public function setPassword($password)
	{
		$this->password = $password;
		return $this;
	}

	/*
	 * Get email
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/*
	 * Set email
	 */
	public function setEmail($email)
	{
		$this->email = $email;
		return $this;
	}

	/*
	 * Get isActive
	 */
	public function getIsActive()
	{
		return $this->isActive;
	}

	/*
	 * Set isActive
	 */
	public function setIsActive($isActive)
	{
		$this->isActive = $isActive;
		return $this;
	}

	public function getSalt()
	{
		// pas besoin de salt puisque nous allons utiliser bcrypt
		// attention si vous utilisez une méthode d'encodage différente !
		// il faudra décommenter les lignes concernant le salt, créer la propriété correspondante, et renvoyer sa valeur dans cette méthode
		return null;
	}

	// modifier la méthode getRoles
	public function getRoles()
	{
		return $this->roles; 
	}

	public function setRoles(array $roles)
	{
		if (!in_array('ROLE_USER', $roles))
		{
			$roles[] = 'ROLE_USER';
		}
		foreach ($roles as $role)
		{
			if(substr($role, 0, 5) !== 'ROLE_') {
				throw new InvalidArgumentException("Chaque rôle doit commencer par 'ROLE_'");
			}
		}
		$this->roles = $roles;
		return $this;
	} 

	public function eraseCredentials()
	{
	}

	/** @see \Serializable::serialize() */
	public function serialize()
	{
		return serialize(array(
			$this->id,
			$this->username,
			$this->password,
			$this->isActive,
			// voir remarques sur salt plus haut
			// $this->salt,
		));
	}

	/** @see \Serializable::unserialize() */
	public function unserialize($serialized)
	{
		list (
			$this->id,
			$this->username,
			$this->password,
			$this->isActive,
			// voir remarques sur salt plus haut
			// $this->salt
		) = unserialize($serialized);
	}

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }
 
    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;
    }

     /*
     * Get created
     */
    public function getCreated()
    {
        return $this->created;
    }

    /*
     * Set created
     */
    public function setCreated($created)
    {
        $this->created = $created;
        return $this;
    }

     /*
     * Get passwordRequestedAt
     */
    public function getPasswordRequestedAt()
    {
        return $this->passwordRequestedAt;
    }

    /*
     * Set passwordRequestedAt
     */
    public function setPasswordRequestedAt($passwordRequestedAt)
    {
        $this->passwordRequestedAt = $passwordRequestedAt;
        return $this;
    }

    /*
     * Get token
     */
    public function getToken()
    {
        return $this->token;
    }

    /*
     * Set token
     */
    public function setToken($token)
    {
        $this->token = $token;
        return $this;
    }


    /*
     * add page
     */
    public function addPage(Page $page)
    {
        $this->pages[] = $page;
    }

    /*
     * get page
     */
    public function getPages()
    {
    	return $this->pages;
    }

    /*
     * get the page related to this user
     */
    public function getMyUserPage()
    {
    	foreach ($this->pages as $key => $page) {
    		if($page->getType() == "user") return $page;
    	}
    }
    /*
     * get the position (coordinates) of the page related to this user
     */
    public function getMyPosition()
    {
    	$page = $this->getMyUserPage();
    	return @$page->getCoordinates() ? $page->getCoordinates() : false;
    }

    public function getImageProfil(){
    	$myPage = $this->getMyUserPage();
    	return $myPage->getImageProfil();
    }

    /*
     * Get isSuperAdmin
     */
    public function isSuperAdmin()
    {
        return isset($this->isSuperAdmin) ? $this->isSuperAdmin : false;
    }

    /*
     * Set isSuperAdmin
     */
    public function setIsSuperAdmin($isSuperAdmin)
    {
        $this->isSuperAdmin = $isSuperAdmin;
        return $this;
    }
    
 //    public function getCaptchaCode()
	// {
	//     return $this->captchaCode;
	// }

	// public function setCaptchaCode($captchaCode)
	// {
	//     $this->captchaCode = $captchaCode;
	// }
	
    /*
     * Anonymifaction instead of remove
     */
    public function anonymify()
    {
        $this->username="";
		$this->password="";
		$this->email="";
		$this->isActive=false;
		$this->plainPassword="";
		$this->token="";
		$this->isSuperAdmin=false;

        return $this;
    }


}

templates/page/blocks/friend-suggestion.html.twig
{% trans_default_domain 'page' %}

<div class="ui-block">
	<div class="ui-block-title">
		<h6 class="title"><i class="fa fa-hand-peace-o"></i> {% trans %}Friend Suggestions{% endtrans %}</h6>
		{# <a href="#" class="more"><svg class="olymp-three-dots-icon"><use xlink:href="{{ asset('icons/icons.svg') }}#olymp-three-dots-icon"></use></svg></a> #}
	</div>

	<ul class="widget w-friend-pages-added notification-list friend-requests">
		{% for friend in friendSuggest %}
		<li class="inline-items">
			<div class="author-thumb d-none d-lg-inline">
				<img src="{{ friend.imageProfilAsset }}" alt="img" height="36">
			</div>
			<div class="notification-event">
				<a href="{{ path("page", {'slug':friend.slug}) }}" 
					class="h6 notification-friend elipsis {% if friend.city == "" %}margin-top-10{% endif %}">
					{{ friend.name }}
				</a>
				{% if friend.city != "" and friend.isConfAuth("SHOW_ADDRESS", app.user.myUserPage) %}
					<span><i class="fa fa-map-marker"></i> {{ friend.city }}</span>
				{% endif %}
			</div>
			<span class="notification-icon">
				<a href="javascript:" class="btn-send-request-friend accept-request" data-slug-page="{{ friend.slug }}"
					data-toggle="modal" data-target="#modal-quickview" title="{% trans %}send friend request{% endtrans %}" >
					{# <span class="icon-add without-text">
						<svg class="olymp-happy-face-icon"><use xlink:href="{{ asset('icons/icons.svg') }}#olymp-happy-face-icon"></use></svg>
					</span> #}
					<i class="fa fa-hand-peace-o padding-5"></i>
				</a>
			</span>
		</li>
		{% endfor %}
	</ul>
</div>

<script>
	$( document ).ready(function() {
		nexxo.initBtnRequest();
	});
</script>

templates/page/blocks/search-res-list.html.twig
{% trans_default_domain 'page' %}

<style>
.container-relation{
	position: absolute;
	top:0px;
	width:40%;
	background: transparent;
}
.label-relation{
	float:left;
	margin: 5px;
	background-color: rgba(35, 35, 35, 0.7);
	padding: 3px 6px;
	border-radius: 40px;
	width: 24px;
	font-size: 11px;
	text-align: center;
	color: white;
	margin-right: 0px;
}
.label-relation i{
	
}
</style>
<div class="res-total-count d-none">{{ totalCount }}</div>
<div  class="row no-margin">
	{% for result in results %}
		<div class="col col-xl-4 col-lg-6 col-md-6 col-sm-6  col-xs-12 col-12">
			<div class="ui-block">
				
				<!-- Friend Item -->
				<div class="friend-item">
					<div class="friend-header-thumb" data-page-type="{{ result.type }}">
						<a href="{{ path('page', {'slug': result.slug}) }}" 
							class="{% if result.imageBanner == "default.png" %}banner-empty{% endif %}">
								<img src="{{ result.imageBannerAssetMin }}" alt="img">
				                
						</a>
						<div class="container-relation">
						{% if app.user != null %}
							{% if result.relations.ImFriend(app.user.myUserPage.slug) == true %} 
								<div class="label-relation" 	
									 data-toggle="tooltip" 
									 {% if result.type == "user" %}	
									 data-original-title="{% trans %}you are friends whith this person{% endtrans %}"{% endif %}
									 {% if result.type != "user" %}	
									 data-original-title="{% trans %}you are member of this page{% endtrans %}"{% endif %}
								>
									<i class="fa fa-hand-peace-o"></i></div>
							{% endif %}
							{% if result.relations.InParticipants(app.user.myUserPage.slug) == true %} 
								<div class="label-relation"><i class="fa fa-hand-o-right"></i></div>
							{% endif %}
							{% if result.relations.InFollows(app.user.myUserPage.slug) == true %} 
								<div class="label-relation"><i class="fa fa-link"></i></div>
							{% endif %}
							{% if result.relations.ImAdminOf(app.user.myUserPage.slug) == true %} 
								<div class="label-relation"><i class="fa fa-user-secret"></i></div>
							{% endif %}
							{% if result.relations.ILike(app.user.myUserPage.slug) == true %} 
								<div class="label-relation"><i class="fa fa-thumbs-o-up"></i></div>
							{% endif %}
						{% endif %}
						</div>

						{% if app.user != null %}
							{% if result.coordinates[0] != "false" and 
								  result.isConfAuth("SHOW_GEOPOS", app.user.myUserPage) and
								  result.id != app.user.myUserPage.id
							 %}
								<button class="btn-open-marker" data-id="{{ result.id }}">
									<i class="fa fa-map-marker letter-blue"></i>
								</button>
							{% endif %}
						{% else %}
							{% if result.getConfAuth("SHOW_GEOPOS") == "CONF_NEXXO" %}
								<button class="btn-open-marker" data-id="{{ result.id }}">
									<i class="fa fa-map-marker letter-blue"></i>
								</button>
							{% endif %}
						{% endif %}
					</div>
				
					<div class="friend-item-content" id="{{ result.slug }}">

						<div class="friend-avatar">
							<div class="author-thumb margin-bottom-5"
								 data-toggle="modal" data-target="#modal-quickview"
								 title="{% trans %}Show quick view{% endtrans %}">
								<a href="javascript:" class="open-quickview" data-type="page" data-id="{{ result.slug }}">
									<img src="{{ result.imageProfilAsset }}" alt="img" height="92">
					                <i class="fa fa-type-page fa-{{ result.faIcon }} letter-{{ result.colorType }} border-b-{{ result.colorType }} border-b-2"></i>
								</a>
							</div>
							<div class="author-content">
								<small class="elipsis">{{ result.tagsStr }}{% if result.tagsStr == "" %}-{% endif %}</small>
								<br>
								<a href="{{ path('page', {'slug': result.slug}) }}" class="h5 author-name elipsis no-margin">
									{{ result.name }}
								</a>
								<br>
								<div class="country elipsis no-margin">
									{% if app.user != null %}
										{% if result.isConfAuth("SHOW_ADDRESS", app.user.myUserPage) and result.city != "" %}
											{% if result.country != "" %}<i class="fa fa-map-marker"></i>{% else %}<br>{% endif %}
											{% if result.city != "" %}{{ result.city }}{% endif %}
											{# if result.streetAddress != "" and result.streetAddress != "" %}, {{ result.streetAddress }}{% endif #}
											{% if result.country != "" and result.country != "" %}, {{ result.country }}{% endif %}
										{% endif %}
										{% if result.city == "" %}-{% endif %}
									{% else %}
										{% if result.getConfAuth("SHOW_ADDRESS") == "CONF_NEXXO" and result.city != "" %}
											{% if result.country != "" %}<i class="fa fa-map-marker"></i>{% else %}<br>{% endif %}
											{% if result.city != "" %}{{ result.city }}{% endif %}
											{# if result.streetAddress != "" and result.streetAddress != "" %}, {{ result.streetAddress }}{% endif #}
											{% if result.country != "" and result.country != "" %}, {{ result.country }}{% endif %}
										{% endif %}
									{% endif %}
								</div>
							</div>
						</div>
				
						<div class="row">

							{% if result.type == "user" %} 
								<span class="friend-count-item">
									<div class="h6 count-item-friend">{{ result.relations.realFriends|length }}</div>
									<div class="title">{% trans %}Friends{% endtrans %}</div>
									{% if app.user != null and result.id != app.user.myUserPage.id %} 
									<a href="javascript:" class="btn btn-blue btn-control btn-send-request-friend" 
									   data-slug-page="{{ result.slug }}"
									   {# data-toggle="tooltip" data-original-title="{% trans %}Ask for friend{% endtrans %}" 
									   data-placement="bottom"#}
									   title="{% trans %}Ask for friend{% endtrans %}"
									   data-toggle="modal" data-target="#modal-quickview">
										<i class="fa fa-hand-peace-o"></i>
									</a>
									{% endif %} 
								</span>
							{% elseif result.type == "event" %} 
								<span class="friend-count-item">
									<div class="h6 count-item-participate">{{ result.relations.participants|length }}</div>
									<div class="title">{% trans %}Participants{% endtrans %}</div>
									{% if app.user != null and result.id != app.user.myUserPage.id %} 
									<a href="javascript:" class="btn btn-blue btn-control btn-send-request-participate" 
									   data-slug-page="{{ result.slug }}"
									   {# data-toggle="tooltip" data-original-title="{% trans %}I want to participate{% endtrans %}"
									   data-placement="bottom" #}
									   title="{% trans %}I want to participate{% endtrans %}"
									   data-toggle="modal" data-target="#modal-quickview">
										<i class="fa fa-group"></i>
									</a>
								{% endif %}
								</span>
							{% else %} 
								<span class="friend-count-item">
									<div class="h6 count-item-friend">{{ result.relations.friends|length }}</div>
									<div class="title">{% trans %}Members{% endtrans %}</div>
									{% if app.user != null and result.id != app.user.myUserPage.id %} 
									<a href="javascript:" class="btn btn-blue btn-control btn-send-request-friend" 
									   data-slug-page="{{ result.slug }}"
									   {# data-toggle="tooltip" data-original-title="{% trans %}Become member{% endtrans %}"
									   data-placement="bottom" #}
									   title="{% trans %}Become member{% endtrans %}"
									   data-toggle="modal" data-target="#modal-quickview">
										<i class="fa fa-hand-peace-o"></i>
									</a>
								{% endif %}
								</span>
							{% endif %} 
							<span class="friend-count-item">
								<div class="h6 count-item-follow">{{ result.relations.followers|length }}</div>
								<div class="title">{% trans %}Followers{% endtrans %}</div>
								{% if app.user != null and result.id != app.user.myUserPage.id %} 
									<a href="javascript:" class="btn btn-purple btn-control btn-send-request-follow" 
								   data-slug-page="{{ result.slug }}"
								   data-slug-page-confirm="true"
								   {# data-toggle="tooltip" data-original-title="{% trans %}Follow this page{% endtrans %}"
								   data-placement="bottom" #}
								   title="{% trans %}Follow this page{% endtrans %}">
									<i class="fa fa-link"></i>
								</a>
								{% endif %}
							</span>
							<span class="friend-count-item">
								<div class="h6 count-item-like">{{ result.relations.likers|length }}</div>
								<div class="title">{% trans %}Likes{% endtrans %}</div>
								{% if app.user != null and result.id != app.user.myUserPage.id %} 
									<a href="javascript:" class="btn btn-blue btn-control btn-send-request-like" 
								   data-slug-page="{{ result.slug }}"
								   data-slug-page-confirm="true"
								   {# data-toggle="tooltip" data-original-title="{% trans %}Like this page{% endtrans %}"
								   data-placement="bottom" #}
								   title="{% trans %}Like this page{% endtrans %}">
								<i class="fa fa-thumbs-o-up"></i>
								</a>
								{% endif %}
							</span>
						</div>
						

						{% if  app.user != null and result.id == app.user.myUserPage.id %}<br>{% endif %}

					</div>
				</div>			
			</div>
		</div>
	{% endfor %}

	{% if results|length == 0 %}
		<div class="col col-12">
			<div class="ui-block padding-15">
				<i class="fa fa-ban"></i> {% trans %}No result{% endtrans %}
			</div>
		</div>
	{% endif %}
</div>

<script>
	searchObj.results  =  {{ jsonRes|json_encode|raw }};
    $( document ).ready(function() {
        searchObj.initListResUi();
    });
</script>